spring.data.mongodb.uri=${DB_URL}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.timeout=500ms
spring.data.redis.connect-timeout=500ms

app.cors.allowed-origin=${REACT_APP_DOMAIN}